/**
 * Copyright (C) 2020-@year@ by Eisi Cnsulting.
 * All rights reserved.
 *
 * Eisi Headquarters:
 * 6 RUE DES DEUX COMMUNES
 * 91480 QUINCY SOUS SENART

 * Created at 05/04/2020 13:32
 * @author Saber Ben Khalifa <saber.khalifa@eisi-consulting.fr>
 **/

export type Feature =
  'ACTIVITY_MANAGEMENT'
  | 'ACTIVITY_TYPE_MANAGEMENT'
  | 'CLIENT_MANAGEMENT'
  | 'CONSULTANT_MANAGEMENT'
  | 'CRA_MANAGEMENT'
  | 'ESN_MANAGEMENT'
  | 'MSG_MANAGEMENT'
  | 'MSGHISTO_MANAGEMENT'
  | 'PROJECT_MANAGEMENT'
  | 'PERMISSION_MANAGEMENT'
  | 'HOLIDAY_MANAGEMENT'
  | 'PAYMENT_MODE_MANAGEMENT'
  | 'FEE_CATEGORY_MANAGEMENT'
  | 'FEE_MANAGEMENT'
  | 'FEE_MANAGEMENT'
  | 'IDENTITY_DOCUMENT_MANAGEMENT'
  | 'CONTRACT_MANAGEMENT'
  | 'PAY_SHEETS_MANAGEMENT'
  | 'SERVICE_NOTE_MANAGEMENT'
  | 'CV_MANAGEMENT'
  | 'PROOF_OF_ABSENCE_MANAGEMENT'
  | 'OTHER_MANAGEMENT';
export type AuthGroup = 'VIEW' | 'UPDATE' | 'CREATE' | 'DELETE';

